### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nicola** [solid/node-solid#1]
- [ ] Refactoring: Move ldnode to node-solid by using `rdf-ext` and `rdf-store-*`
- [ ] need to fix POST on rdf-store-fs (ping @bergos)
- [ ] need to add support to ldp (ping @bergos)
- [ ] Fix ACL tests
- [ ] solid-cli: Make command line tool `solid-cli` a separate repo from the library, in this way we can have separate support and separate testing - we had issues in the past
